

                <table>
                <thead>
                    <tr>
                        <th>Naziv</th>
                        <th>Adresa</th>
                        <th>Zona</th>
                        <th>Operater</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach($podaci as $red){
                        include 'NPbaza.phtml';
                    }
                    
                    ?>
                </tbody>
            </table>



