<!-- Početak izbornik -->
<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title"><?php echo APP::config('nazivAPP'); ?></div>
</div>
<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text show-for-large">
            <?php echo APP::config('nazivAPP'); ?>
            </li>
            <li><a href="/">Početna</a></li>
            <li><a href="/Mapa/index">Mapa</a></li>
            <li><a href="/index/Era">Era</a></li>
            <?php if(isset($_SESSION['operater'])):?>
                <li><a href="/nadzornaploca/index">Nadzorna ploča</a></li>
                <?php if(isset($_SESSION['operater']) && $_SESSION['operater']->uloga==='admin'):?>
                    <li><a href="/operater/index">Operateri</a></li>
                    <li><a href="/unos/index">Dodaj</a></li>
                <?php else:?>
                    <li><a href="/nadzornaploca/profil">DummyCode</a></li>
                <?php endif;?>
            <?php endif;?>
            <?php if(isset($_SESSION['operater']) && $_SESSION['operater']->uloga!=='admin'):?>
                <li><a href="/index/onama">O nama</a></li>
                
                <?php endif;?>
            

<!-- OVDJE IDE IF ZA KORISNIKA I OPERATER/ADMINA -->
            <?php if(isset($_SESSION['operater']) && $_SESSION['operater']->uloga==='admin'):?>
                <li>
           <a href="/nadzornaploca/profil">Profil 
          </a>
           </li>
           <?php else:?>

        <?php endif;?>



       





        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
           
                <?php if(!isset($_SESSION['operater']) OR $_SESSION['operater']->uloga!=='admin'):?>
                <li>
                <a href="/index/prijava">Prijava</a>
                </li>
                <li>
                <a href="/index/registracija">Registriraj se</a>
                </li>
                <li><a href="/index/admin">Admin</a></li>
            <?php else:?>
                <li>
                <a href="/index/odjava">Odjavi 
               </a>
                </li>
            <?php endif;?>
                
        </ul>
    </div>
</div>
<!-- Kraj izbornik -->