



<!DOCTYPE html >
  <head><meta charset="euc-jp">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

    <title>Info-Parking</title>
    <script src="<?php echo APP::config('url'); ?>public/js/vendor/jquery.js"></script>
    <script src="<?php echo APP::config('url'); ?>public/js/vendor/what-input.js"></script>
    <script src="<?php echo APP::config('url'); ?>public/js/vendor/foundation.js"></script>
    <script src="<?php echo APP::config('url'); ?>public/js/vendor/foundation.js"></script>
    <script src="<?php echo APP::config('url'); ?>public/js/app.js"></script>
    <script src="<?php echo APP::config('url'); ?>javascript/googlemap.js"></script>
	<style type="text/css">
		.container {
			height: 450px;
		}
		#map {
			width: 75%;
			height: 70%;
			border: 1px solid blue;
		}
		#data, #allData {
			display: none;
		}
	</style>
  </head>

<html>

  <body>
    <div class="container">
		<center><h1>Mapa info-parking</h1></center>
		<form method="get" action="/">
    	<button class="button" type="submit">Back</button>
		</form>

		<?php
			require_once ('model/Mapa_1.php');
			$map = new mapa_1;
			$coll = $map->getCollegesBlankLatLng();
			$coll = json_encode($coll, true);
			echo '<div id="data">' . $coll . '</div>';

			$allData = $map->getAllColleges();
			$allData = json_encode($allData, true);
			echo '<div id="allData">' . $allData . '</div>';
		 ?>
		<div id="map"></div>
	</div>

  </body>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBo6VrULwKmbd6Lvey_y3U_CO4gCcBCIOU&callback=loadMap">
</script>
</html>
