



		<!-- Main -->
			<section id="main">
				<div class="inner">

				<!-- One -->
					<section id="one" class="wrapper style1">

						<div class="image fit flush">
							<img src="images/pic02.jpg" alt="" />
						</div>
						<header class="special">
							<h2>Dobrodošli na info-parking webstranicu</h2>
						</header>
						<div class="content">
							<p>Ovdje možete naći sve informacije i mjesta o dostupnim parkirnim mjestima u Gradu Osijeku.</p>
							<p>Ukoliko imate koje pitanje slobodno nam se obratite na mail adresu </p>
						</div>
					</section>

				</div>
			</section>
